### ISSUE TITLE
Bottom property on Text

### ISSUE THREAD

**Issue by vljukap98** [johnfercher/maroto#480] opened 2024-10-04 10:56 UTC
**Is your feature request related to a problem? Please describe.**

This might not be a whole feature request, but I was wondering some things about the 'bottom' property on Text. I saw a couple of issues previously reported regarding this topic. Now I am aware that bottom doesn't exist in fpdf, therefore not in gofpdf, but then in your code samples for 'AddAutoRow' here - [https://maroto.io/#/v2/features/autorow?id=auto-row](https://maroto.io/#/v2/features/autorow?id=auto-row) - there is shown usage of said property. When I copy the snippet and try to execute it I obviously get an error regarding "Bottom" property. Then, you also show a result of running the same snippet, and it looks like the row where you're setting said property works:
![image](https://github.com/user-attachments/assets/e51b81ac-0ddb-44c9-aa39-a1210ac93340)

**Describe the solution you'd like**
A solution that enables usage of Bottom property, or an explanation how did it work in the documentation.

**Describe alternatives you've considered**

I tried setting VerticalPadding property on Text, but it seems that doesn't do the trick for me. I'm either doing something wrong or it isn't related to my problem/request.

**Additional context**
-

**Comment by vljukap98** [comment] 2024-10-07 10:47
I'm just seeing that some of the commits inside the master branch were about this "Bottom" padding and I saw this PR [https://github.com/johnfercher/maroto/pull/478](https://github.com/johnfercher/maroto/pull/478) that seems to fulfill my request. I think it's just a bit confusing that the documentation shows that it's possible to use said property, but in the latest release, 2.1.4 that is, it's not - yet I presume. I think you should try to make that clear when you're doing merges or documentation updates.

**Comment by vljukap98** [comment] 2024-10-07 13:21
I was trying to upgrade the package with:

`go get github.com/johnfercher/maroto/v2@v2.1.5`

But I'm getting the following error:
`go: github.com/johnfercher/maroto/v2@v2.1.5: github.com/johnfercher/maroto/v2@v2.1.5: invalid version: unknown revision v2.1.5`

**Comment by johnfercher** [comment] 2024-10-08 02:40
Sorry bro, I generated a wrong named version. Try again, please. https://github.com/johnfercher/maroto/releases/tag/v2.1.5

**Comment by vljukap98** [comment] 2024-10-08 07:26
It looks like Bottom on Text property works, in some way. I'm not sure if you had the time to test this, maybe I'm doing something wrong, but I get a "buggy" pdf output after just adding Bottom: 1 on my text. This is the pdf (check out pages 7-11):
[test.pdf](https://github.com/user-attachments/files/17289449/test.pdf)

The code I'm using to generate this:

```go
var loremIpsum = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n\n" +
	" Pellentesque vitae ligula sit amet nisl vehicula ultrices egestas a massa.\n\n" +
	" Nullam vel arcu suscipit, eleifend leo at, gravida risus. Nullam lacinia tortor\n\n" +
	" eget tincidunt sodales. Proin tristique rutrum ullamcorper.\n\n" +
	" Duis ut quam condimentum, rhoncus quam sit amet, lacinia arcu.\n\n" +
	" Nam aliquet nulla ac leo rhoncus, tempor luctus mauris varius.\n\n" +
	" Suspendisse erat libero, bibendum venenatis lacus quis, cursus rutrum quam.\n\n" +
	" Donec est libero, efficitur nec laoreet eu, efficitur ut arcu.\n\n" +
	" Cras aliquam risus et dolor rhoncus, blandit blandit ex ullamcorper.\n\n" +
	" Nullam eleifend elementum dolor quis commodo. Sed auctor at felis finibus scelerisque.\n\n" +
	" Donec eget lobortis est. Maecenas vitae laoreet elit, vitae mollis enim.\n\n"

func main() {
	generatePdf()
}

func generatePdf() {
	m := GetMaroto()
	document, err := m.Generate()
	if err != nil {
		log.Fatal(err.Error())
	}

	err = document.Save("test.pdf")
	if err != nil {
		log.Fatal(err.Error())
	}

	err = document.GetReport().Save("test.txt")
	if err != nil {
		log.Fatal(err.Error())
	}
}

func GetMaroto() core.Maroto {
	customFonts, err := repository.
		New().
		AddUTF8Font("OpenSans", fontstyle.Normal, "OpenSans.ttf").
		Load()

	if err != nil {
		log.Fatal(err.Error())
	}

	cfg := config.NewBuilder().
		WithCustomFonts(customFonts).
		WithConcurrentMode(7).
		WithOrientation(orientation.Horizontal).
		Build()

	mrt := maroto.New(cfg)
	m := maroto.NewMetricsDecorator(mrt)

	err = m.RegisterHeader(getPageHeader())
	if err != nil {
		log.Fatal(err.Error())
	}

	err = m.RegisterFooter(getPageFooter())
	if err != nil {
		log.Fatal(err.Error())
	}

	for i := 0; i < 100; i++ {
		m.AddAutoRow(
			text.NewCol(
				4,
				getRandomSubstring(),
				props.Text{
					Align:             align.Left,
					Top:               1,
					Bottom:            1,
					BreakLineStrategy: breakline.EmptySpaceStrategy,
				}).
				WithStyle(&props.Cell{
					BorderType:      border.Full,
					BorderColor:     &props.BlackColor,
					BorderThickness: 0.1}),
			text.NewCol(
				4,
				getRandomSubstring(),
				props.Text{
					Size:              5,
					Align:             align.Left,
					Top:               1,
					Bottom:            1,
					BreakLineStrategy: breakline.EmptySpaceStrategy,
				}).
				WithStyle(&props.Cell{
					BorderType:      border.Full,
					BorderColor:     &props.BlackColor,
					BorderThickness: 0.1,
				}),
			getImageColumn(i),
		)

	}

	return m
}

func getImageColumn(i int) core.Col {
	imagePath := ""

	if i%5 == 0 {
		imagePath = "pexels-chokniti-khongchum-1197604-2280547.jpg"
	} else if i%7 == 0 {
		imagePath = "pexels-cottonbro-10202723.jpg"
	} else if i%3 == 0 {
		imagePath = "alice.jpg"
	} else {
		imagePath = "pexels-pixabay-276267.jpg"
	}

	if i%3 == 0 {
		return image.NewFromFileCol(
			4,
			imagePath,
			props.Rect{
				Center:             true,
				JustReferenceWidth: true,
				Percent:            50,
			}).
			WithStyle(&props.Cell{
				BorderType:      border.Full,
				BorderColor:     &props.BlackColor,
				BorderThickness: 0.1,
			})
	} else {
		return text.NewCol(
			4,
			getRandomSubstring(),
			props.Text{
				Align:             align.Left,
				Top:               1,
				Bottom:            1,
				BreakLineStrategy: breakline.EmptySpaceStrategy,
			}).
			WithStyle(&props.Cell{
				BorderType:      border.Full,
				BorderColor:     &props.BlackColor,
				BorderThickness: 0.1,
			})
	}
}

func getRandomSubstring() string {
	firstIdx := rand.IntN(len(loremIpsum))
	return loremIpsum[0:firstIdx]
}

func getPageHeader() core.Row {
	return row.New(5).Add(
		text.NewCol(
			4,
			"test",
			props.Text{
				Top:    1,
				Bottom: 1,
				Align:  align.Center,
				Color:  &props.WhiteColor,
				Style:  fontstyle.Bold,
			}),
		text.NewCol(
			4,
			"test",
			props.Text{
				Top:    1,
				Bottom: 1,
				Align:  align.Center,
				Color:  &props.WhiteColor,
				Style:  fontstyle.Bold,
			}),
		text.NewCol(
			4,
			"test",
			props.Text{
				Top:    1,
				Bottom: 1,
				Align:  align.Center,
				Style:  fontstyle.Bold,
				Color:  &props.WhiteColor,
			}),
	).
		WithStyle(&props.Cell{
			BorderType:      border.Full,
			BorderColor:     &props.BlackColor,
			BorderThickness: 0.1,
			BackgroundColor: &props.BlackColor,
		})
}

func getPageFooter() core.Row {
	return row.New(20).Add(
		col.New(12).Add(
			text.New("Tel: 12 345 12345-1234", props.Text{
				Top:   13,
				Style: fontstyle.BoldItalic,
				Size:  8,
				Align: align.Left,
			}),
			text.New("www.mycompany.com", props.Text{
				Top:   16,
				Style: fontstyle.BoldItalic,
				Size:  8,
				Align: align.Left,
			}),
		),
	)
}
```
I thought it could be the images, but if I don't put images in the third column and to the exact same thing as in previous 2 columns the pdf is still not satisfactory (page 19):
[test.pdf](https://github.com/user-attachments/files/17289493/test.pdf)

After removing Bottom: 1, all data sits perfectly in each of its belonging cell, but then again visually bottom padding is needed because letters like p, g, y overflow over the cell's border which is why I opened this in the first place.

**Comment by johnfercher** [comment] 2024-10-08 14:04
This behavior only occurs with autorow? or this alse occur with row?

**Comment by vljukap98** [comment] 2024-10-10 08:21
I'm not quite sure where it happens, maybe something with calculating row heights when rows with fixed height exist in header/footer. I was playing around last few days and I have small header/footer, so it looks fine.

**Comment by vljukap98** [comment] 2024-10-17 08:54
I think it might has to do something with font style: Bold in combination with putting images in some cells?
![image](https://github.com/user-attachments/assets/2a59ff87-d6c1-4c3a-8997-4679962783df)
[test2.pdf](https://github.com/user-attachments/files/17409180/test2.pdf)

**Comment by Fernando-hub527** [comment] 2024-10-20 18:50
Hello!

I  would like to help you with the problem. Could you send me the files you used in your example? That way, I can try to replicate your results and figure out what’s going on.

**Comment by vljukap98** [comment] 2024-10-21 10:44
These are the files used (including .go file) - https://mega.nz/folder/TstgkKCY#CdDYrTrnVcOzGAxUcU__mg

**Comment by Fernando-hub527** [comment] 2024-10-22 00:59
Hello!
I did some tests:

![Captura](https://github.com/user-attachments/assets/68ba3b3d-4352-4cfc-8e1a-c26a1e0131d4)

The bootom property seems to be working fine.
I'm using Maroto version 2.2.1. Maybe the issue is with the version you're using—can you check? If that's not it, I can take another look to figure out what's going on.

**Comment by ummm288** [comment] 2024-10-24 19:54
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Fernando-hub527** [comment] 2024-11-30 20:23
Hi @vljukap98, I did some testing, and it looks like the issue is related to the version of Maroto you're using. I'll go ahead and close this issue, but if you believe this isn't the cause of the error, feel free to reopen it.

**Closed by Fernando-hub527** 2024-11-30 20:23 UTC
